# Generated by Django 2.2.4 on 2019-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('stage', models.IntegerField(null=True)),
                ('method', models.TextField()),
                ('verdict', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
